# Cargo ビルド設定
[build]
rustflags = [
    "-C", "target-cpu=native",     # CPUネイティブ命令使用
    "-C", "prefer-dynamic=no",     # 静的リンク優先
]

# Note: Target-specific SIMD features (AVX2, FMA, NEON) have been removed
# per project antipattern rules. The compiler's auto-vectorization with
# target-cpu=native is sufficient for optimal performance.
