name: Deploy Documentation to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install uv
        run: pip install uv
      
      - name: Install dependencies
        run: uv sync --extra docs
      
      - name: Build English docs (default)
        run: |
          cd docs/en
          sphinx-build -b html . _build/html
      
      - name: Build Japanese docs
        run: |
          cd docs/ja
          sphinx-build -b html . _build/html
      
      - name: Combine builds for deployment
        run: |
          # Create deployment directory
          mkdir -p docs/_site
          # English version at root
          cp -r docs/en/_build/html/* docs/_site/
          # Japanese version in subdirectory
          cp -r docs/ja/_build/html docs/_site/ja
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/_site
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
