name: Performance Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  performance:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Install dependencies
      run: |
        uv sync --all-extras
        uv run maturin develop --release
    
    - name: Download baseline artifact
      uses: actions/download-artifact@v4
      with:
        name: performance-baseline
        path: tests/performance/
      continue-on-error: true
    
    - name: Check baseline status
      id: baseline-check
      run: |
        if [ -f tests/performance/baseline.json ]; then
          echo "Baseline exists"
          echo "baseline_exists=true" >> $GITHUB_OUTPUT
        else
          echo "No baseline found - will create initial baseline"
          echo "baseline_exists=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Run performance tests
      run: |
        uv run pytest tests/performance/test_all_benchmarks.py -v --benchmark-only
    
    - name: Check for performance regressions
      if: steps.baseline-check.outputs.baseline_exists == 'true'
      run: |
        echo "Checking for performance regressions..."
        uv run python tests/performance/check_regression.py
    
    - name: Create initial baseline
      if: steps.baseline-check.outputs.baseline_exists == 'false' && github.ref == 'refs/heads/main'
      run: |
        echo "Creating initial baseline from test results..."
        uv run python tests/performance/update_baseline.py
    
    - name: Skip regression check (no baseline)
      if: steps.baseline-check.outputs.baseline_exists == 'false' && github.ref != 'refs/heads/main'
      run: |
        echo "⚠️ No baseline available for comparison."
        echo "Performance regression check skipped."
        echo "Baseline will be created when merged to main."
    
    - name: Update baseline (main branch only)
      if: github.ref == 'refs/heads/main' && success() && steps.baseline-check.outputs.baseline_exists == 'true'
      run: |
        echo "Updating baseline for main branch..."
        uv run python tests/performance/update_baseline.py
    
    - name: Upload baseline artifact
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: performance-baseline
        path: tests/performance/baseline.json
        retention-days: 90