name: Performance Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  performance:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Install dependencies
      run: |
        uv sync --all-extras
        uv run maturin develop --release
    
    # Baseline management removed - benchmarks/ directory is deprecated
    # See tests/performance/ for current benchmark implementation
    
    - name: Run performance tests
      run: |
        uv run pytest tests/performance/test_all_benchmarks.py -v --benchmark-only
    
    # Performance guard removed - benchmarks/ directory is deprecated
    
    # Baseline update removed - benchmarks/ directory is deprecated