name: Performance Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  performance:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Install dependencies
      run: |
        uv sync --all-extras
        uv run maturin develop --release
    
    - name: Download baseline artifact
      if: github.event_name == 'pull_request'
      uses: actions/download-artifact@v4
      with:
        name: performance-baseline
        path: tests/performance/
      continue-on-error: true
    
    - name: Create initial baseline if needed
      if: github.ref == 'refs/heads/main'
      run: |
        if [ ! -f tests/performance/baseline.json ]; then
          echo "Creating initial baseline..."
          # Run tests first to generate latest.json
          uv run pytest tests/performance/test_all_benchmarks.py -v --benchmark-only
          uv run python tests/performance/update_baseline.py
        fi
    
    - name: Run performance tests
      run: |
        uv run pytest tests/performance/test_all_benchmarks.py -v --benchmark-only
    
    - name: Check for performance regressions
      run: |
        # NumPy+SciPyはCI環境で変動が大きいため、閾値を緩める（初回実行時）
        if [ ! -f tests/performance/baseline.json ]; then
          echo "Note: First run, using relaxed threshold"
          uv run python tests/performance/check_regression.py --threshold 1.5
        else
          uv run python tests/performance/check_regression.py
        fi
    
    - name: Update baseline (main branch only)
      if: github.ref == 'refs/heads/main' && success()
      run: |
        echo "Updating baseline for main branch..."
        uv run python tests/performance/update_baseline.py
    
    - name: Upload baseline artifact
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: performance-baseline
        path: tests/performance/baseline.json
        retention-days: 90